// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwg7bGh9uoSvjsH3r1CmJVdiCWorQPwUY',
    appId: '1:770888774283:web:9ae6c68526cb3c8bf45a8e',
    messagingSenderId: '770888774283',
    projectId: 'firebsae-test-bc57a',
    authDomain: 'firebsae-test-bc57a.firebaseapp.com',
    storageBucket: 'firebsae-test-bc57a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTztw-A7kH9rZGID48j6FXE-1ylGzDyp8',
    appId: '1:770888774283:android:374f35285b85da94f45a8e',
    messagingSenderId: '770888774283',
    projectId: 'firebsae-test-bc57a',
    storageBucket: 'firebsae-test-bc57a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyS1kislEJ28QHvzGsKggE0CpIaRjPxeI',
    appId: '1:770888774283:ios:33014fd431cba83cf45a8e',
    messagingSenderId: '770888774283',
    projectId: 'firebsae-test-bc57a',
    storageBucket: 'firebsae-test-bc57a.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyS1kislEJ28QHvzGsKggE0CpIaRjPxeI',
    appId: '1:770888774283:ios:58f237c6bb4a3855f45a8e',
    messagingSenderId: '770888774283',
    projectId: 'firebsae-test-bc57a',
    storageBucket: 'firebsae-test-bc57a.appspot.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
